### PR TITLE
upgrade to latestet stackage snapshot, remove unneeded extra deps

### PR DESCRIPTION
**Pull request by skogsbaer**

### CODE REVIEW

**Comment by dmvianna** [comment]
Thank you, Stefan. Could you update `.github/workflows/stack.yml` too please? I'll be delighted to merge your PR.

**Comment by skogsbaer** [comment]
Ok, also update the resolver for CI

**Comment by skogsbaer** [comment]
I also would like to check against nightly-2024-09-12 so that we can bring csv-conduit to stackage.

**Comment by dmvianna** [comment]
You know the motions, happy to have it added to CI as well.

**Pull request merged**
