### PR TITLE
Fix GHC96/mtl compatibility

### PR DESCRIPTION
**Pull request by kfigiela**

### CODE REVIEW

**Comment by ysangkok** [comment]
This is similar to #46 and #47 which weren't reviewed, so I closed them. @kfigiela , I think if you wanted to, you could [take over the package](https://wiki.haskell.org/Taking_over_a_package).

**Comment by ysangkok** [comment]
@kfigiela I suppose you would rather not take over the package?

**Review by dmvianna — APPROVED** [review]

**Review by dmvianna — CHANGES_REQUESTED** [review]
I'm working on a fork, and I noticed more problems than just this.

- Stack needs to be bumped to a version that contains the new GHC;
- `return` must be removed
- The test has issues too.
- Ideally we would have explicit imports

This repo is very unloved.

**Comment by ysangkok** [comment]
Thank you for working on this @dmvianna !

**Comment by dmvianna** [comment]
I'm happy to take over. I just need to learn more about Travis so we could continue to support older GHC. I intend to do that today.

Then what? I submit a PR?

**Comment by ysangkok** [comment]
I think it would make sense to follow the procedure here:

https://wiki.haskell.org/Taking_over_a_package

Since all maintainers are unavailable, you can fork the repo and then update the metadata to point at the new repo.

**Comment by dmvianna** [comment]
Fixed in #51

**Pull request closed without merging**
